#!/bin/sh
set -e

echo "[INFO] Starting MAX! to MQTT Bridge..."

# If we needed to map options.json to ENV vars, we would do it here using jq.
# However, our Go binary reads /data/options.json directly.
# (This file is automatically generated by the Home Assistant Supervisor at runtime).
# This script is kept for future extensibility (e.g. setting up udev rules or debug loops).

exec /app/max2mqtt
